server:
  port: 9001
spring:
  data:
    mongodb:
      uri: mongodb+srv://auth:8gBHNu3VlX8yJ9pe@capacytordev.ln5upml.mongodb.net/?retryWrites=true&w=majority
      database: forms
dev:
  capacytor:
    network:
      base: http://localhost:9001